import Foundation

/// Protocol that types can conform to for structured generation
public protocol GeneratableType: Codable {
  /// Human-readable description of what this type represents
  static var typeDescription: String { get }

  /// JSON schema for this type (generated by @Generatable macro)
  static func jsonSchema() throws -> String
}
